#### Que 1 : Count all letters, digits, and special symbols from a given string
str1 = "I@#ma26rt^&ic5us"

In [9]:
str1 = "I@#ma26rt^&ic5us"
lst = list(str1)
count_digit=0
count_letters = 0 
count_syb = 0 
for i in lst:
    if i.isnumeric()==True:
        count_digit+=1
    elif i.isalpha() ==True:
        count_letters+=1
    else: 
        count_syb+=1     
print("Number of digits in string: ",count_digit)
print("Number of letters in string: ",count_letters)
print("Number of special symbols in string: ",count_syb)

Number of digits in string:  3
Number of letters in string:  9
Number of special symbols in string:  4

#### Que2 : Write a Python program to find numbers divisible by nineteen or thirteen from a list of numbers using Lambda.
a=[19, 65, 57, 39, 152, 639, 121, 44, 90, 190]

In [1]:
# List of numbers
a = [19, 65, 57, 39, 152, 639, 121, 44, 90, 190]

# Filter numbers divisible by 19 or 13
result = list(filter(lambda x: x % 19 == 0 or x % 13 == 0, a))

# Print the result
print("Numbers divisible by 19 or 13:", result)

Numbers divisible by 19 or 13: [19, 65, 57, 39, 152, 190]

### Que 3: Find all of the words in a string that are less than 5 letters
string = "Practice Problems to Drill List Comprehension in Your Head."

In [7]:
string = "Practice Problems to Drill List Comprehension in Your Head."
lst = string.split(' ')

count = 0
small_word = []
for i in lst:
    if len(i)<5:
        small_word.append(i)
        count+=1
print("List of words having less than 5 letters:",small_word)
print("number of words having less than 5 letters:", count)

List of words having less than 5 letters: ['to', 'List', 'in', 'Your']
number of words having less than 5 letters: 4

### Que 4: Calculate income tax for the given income by adhering to the below rules
Expected Output:
For example, suppose the taxable income is 45000 the income tax payable is
10000 0% + 10000 10% + 25000 20% = $6000.

In [18]:
def calculate_tax(income):
    if income <=10000:
        print("Not in tax slab")
    elif income>10000 and income<=20000: 
        tax = 10000*(10/100)
    else: 
        tax = 10000*(10/100) + (income - 10000-10000) * (20/100)
    return tax

In [28]:
income = int(input("Enter your income here:"))
tax = calculate_tax(income)
print("yout payable tax is: ",tax)

Enter your income here: 45000

yout payable tax is:  6000.0

### Que 5: Given below are the list of positive and negative words. Also a list of tweets is provided. Separate out the positive and negative comments¶
positive = ['good','awesome', 'best', 'nice']
negative = ['worst','awful', 'bad']
tweets = ['This government policies are good', 'bad implementation', 'The way he played showed that he is one of the best players in the world', 'Her acting in the play was awesome', 'The wine tastes awful', 'It's nice to hear this little kid's laugh']

In [35]:
positive = ['good','awesome', 'best', 'nice'] 
negative = ['worst','awful', 'bad']
tweets = ['This government policies are good', 'bad implementation', 'The way he played showed that he is one of the best players in the world', 
          'Her acting in the play was awesome', 
          'The wine tastes awful',"It's nice to hear this little kid's laugh"]
possitive_comment = []
negative_comment = []

for tweet in tweets : 
    tweet = tweet.lower()
    if any(word in tweet for word in positive):
        possitive_comment.append(tweet)
    elif any(word in tweet for word in negative):
        negative_comment.append(tweet)

print("Possitive comment: ")
print("\n".join(possitive_comment))
print("\n Negative comment: ")
print("\n".join(negative_comment))

Possitive comment:
this government policies are good
the way he played showed that he is one of the best players in the world
her acting in the play was awesome
it's nice to hear this little kid's laugh

 Negative comment:
bad implementation
the wine tastes awful

###Que6 : Extend nested list by adding the sublist
You have been given a nested list. 
Write a program to extend it by adding the sublist ["h", "i", "j"] in such a way that it will look like the following list.


list1 = ["a", "b", ["c", ["d", "e", ["f", "g"], "k"], "l"], "m", "n"]
sub list to add
sub_list = ["h", "i", "j"]
expected output =['a', 'b', ['c', ['d', 'e', ['f', 'g', 'h', 'i', 'j'], 'k'], 'l'], 'm', 'n']
Remove and add item in a list
Write a program to remove the item present at index 4 and add it to the 2nd position and at the end of the list.
list1 = [54, 44, 27, 79, 91, 41]

In [74]:
list1 = ["a", "b", ["c", ["d", "e", ["f", "g"], "k"], "l"], "m", "n"]

sub_list = ["h", "i", "j"]


list1[2][1][2].extend(sub_list)


print("Updated List:", list1)

Updated List: ['a', 'b', ['c', ['d', 'e', ['f', 'g', 'h', 'i', 'j'], 'k'], 'l'], 'm', 'n']

In [75]:
list2 = [54, 44, 27, 79, 91, 41]
n = list2[4]
list2.remove(n)
list2.insert(2,n)
list2.insert(len(list2),n)
print(list2)

[54, 44, 91, 27, 79, 41, 91]

### Que : 7 Load the iris dataset. 
Find only those records whose sepal_length = 5.1 and sepal_width = 3.5

Check for Maximum petal_length and convert it in to 7.2 and min petal_length and convert it in to 1.2

In [81]:
import pandas as pd
df = pd.read_csv(r"D:\[ Learning ] _ DataScience\Imarticus\iris.data.csv",header=None)
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [94]:
df[(df['sepal_length'] == 5.1) & (df['sepal_width'] == 3.5)]

    sepal_length  sepal_width  petal_length  petal_width      species
0            5.1          3.5           1.4          0.2  Iris-setosa
17           5.1          3.5           1.4          0.3  Iris-setosa

In [100]:

max_petal_length = df['petal_length'].max()
min_petal_length = df['petal_length'].min()


df.loc[df['petal_length'] == max_petal_length, 'petal_length'] = 7.2


df.loc[df['petal_length'] == min_petal_length, 'petal_length'] = 1.2

df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

### Que 8 : Perform right join to combine values based on the 'ID' in the two dataframes
Use the dataframe given below, Read the DataFrame with the help of clipboard function.

In [106]:
df1 = pd.DataFrame()
df1['ID'] = [101,102,103,104,105,106,107]
df1['Candidate_Name'] = ['Alex','Amy','Allen','Alice','James','Sara','Mia']
df1['Subject'] = ['History','English','Geography','German','History','German','English']

df2 = pd.DataFrame()
df2['ID'] = [101,102,103,104,105,108]
df2['City'] = ['Delhi','Mumbai','Delhi','Chennai','Hyderabad','Delhi']
df2['Subject_Score'] = [89,78,77,87,87,84]

In [108]:
df = pd.merge(df1,df2,on='ID',how='right')
df

    ID Candidate_Name    Subject       City  Subject_Score
0  101           Alex    History      Delhi             89
1  102            Amy    English     Mumbai             78
2  103          Allen  Geography      Delhi             77
3  104          Alice     German    Chennai             87
4  105          James    History  Hyderabad             87
5  108            NaN        NaN      Delhi             84